-- =====================================================================
-- 1. TABLA ROL (Catálogo del Sistema)
-- =====================================================================
CREATE TABLE ROL (
    id_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_rol PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL CONSTRAINT uq_rol_nombre UNIQUE,
    descripcion VARCHAR2(200),
    estado VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL CONSTRAINT ck_rol_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- =====================================================================
-- 2. TABLA PERSONA (Identidad Física de Personas y Expedientes Familiares)
-- =====================================================================
CREATE TABLE PERSONA (
    id_persona NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_persona PRIMARY KEY,
    nombres VARCHAR2(80) NOT NULL,
    apellidos VARCHAR2(80) NOT NULL,
    dpi VARCHAR2(13) CONSTRAINT uq_persona_dpi UNIQUE,
    identificacion_alternativa VARCHAR2(30) CONSTRAINT uq_persona_ident_alt UNIQUE,
    telefono VARCHAR2(20),
    correo VARCHAR2(120) CONSTRAINT uq_persona_correo UNIQUE,
    fecha_nacimiento DATE,
    estado VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL CONSTRAINT ck_persona_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_persona_identificacion CHECK (dpi IS NOT NULL OR identificacion_alternativa IS NOT NULL)
);

-- =====================================================================
-- 3. TABLA USUARIO (Credenciales, JWT y Seguridad Robusta)
-- =====================================================================
CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_usuario PRIMARY KEY,
    id_persona NUMBER NOT NULL CONSTRAINT uq_usuario_persona UNIQUE,
    id_rol NUMBER NOT NULL,
    nombre_usuario VARCHAR2(50) NOT NULL CONSTRAINT uq_usuario_nombre UNIQUE,
    contrasena VARCHAR2(255) NOT NULL,
    
    -- Campos de Seguridad Avanzada (Flujo Auth Robusto)
    es_verificado VARCHAR2(2) DEFAULT 'NO' NOT NULL CONSTRAINT ck_usuario_verificado CHECK (es_verificado IN ('SI', 'NO')),
    codigo_verificacion VARCHAR2(6),
    expiracion_codigo TIMESTAMP,
    token_recuperacion VARCHAR2(100),
    expiracion_token TIMESTAMP,
    ultimo_login TIMESTAMP,
    
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    estado VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL CONSTRAINT ck_usuario_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    
    CONSTRAINT fk_usuario_persona FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES ROL (id_rol)
);

-- =====================================================================
-- 4. TABLA CASA
-- =====================================================================
CREATE TABLE CASA (
    id_casa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_casa PRIMARY KEY,
    id_propietario NUMBER NOT NULL,
    numero_casa VARCHAR2(20) NOT NULL CONSTRAINT uq_casa_numero UNIQUE,
    bloque VARCHAR2(30) NOT NULL,
    direccion VARCHAR2(150) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL CONSTRAINT ck_casa_estado CHECK (estado IN ('DISPONIBLE', 'OCUPADA', 'INACTIVA')),
    creado_por NUMBER,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    modificado_por NUMBER,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_casa_propietario FOREIGN KEY (id_propietario) REFERENCES PERSONA (id_persona),
    CONSTRAINT fk_casa_creado_por FOREIGN KEY (creado_por) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_casa_modificado_por FOREIGN KEY (modificado_por) REFERENCES USUARIO (id_usuario)
);

-- =====================================================================
-- 5. TABLA RESIDENTE (Habitantes y Núcleo Familiar)
-- =====================================================================
CREATE TABLE RESIDENTE (
    id_residente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_residente PRIMARY KEY,
    id_persona NUMBER NOT NULL,
    id_casa NUMBER NOT NULL,
    tipo_residente VARCHAR2(15) NOT NULL CONSTRAINT ck_residente_tipo CHECK (tipo_residente IN ('PROPIETARIO', 'INQUILINO', 'FAMILIAR', 'OTRO')),
    fecha_ingreso DATE DEFAULT SYSDATE NOT NULL,
    fecha_salida DATE,
    es_principal VARCHAR2(2) DEFAULT 'NO' NOT NULL CONSTRAINT ck_residente_principal CHECK (es_principal IN ('SI', 'NO')),
    estado VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL CONSTRAINT ck_residente_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT uq_persona_casa UNIQUE (id_persona, id_casa),
    CONSTRAINT ck_residente_fechas CHECK (fecha_salida IS NULL OR fecha_salida >= fecha_ingreso),
    CONSTRAINT fk_residente_persona FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona),
    CONSTRAINT fk_residente_casa FOREIGN KEY (id_casa) REFERENCES CASA (id_casa)
);

-- =====================================================================
-- 6. TABLA MULTA
-- =====================================================================
CREATE TABLE MULTA (
    id_multa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_multa PRIMARY KEY,
    id_casa NUMBER NOT NULL,
    motivo VARCHAR2(250) NOT NULL,
    monto NUMBER(10,2) NOT NULL CONSTRAINT ck_multa_monto CHECK (monto > 0),
    fecha_multa DATE DEFAULT SYSDATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL CONSTRAINT ck_multa_estado CHECK (estado IN ('PENDIENTE', 'PAGADA', 'ANULADA', 'VENCIDA')),
    creado_por NUMBER,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    modificado_por NUMBER,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT ck_multa_fechas CHECK (fecha_vencimiento >= fecha_multa),
    CONSTRAINT fk_multa_casa FOREIGN KEY (id_casa) REFERENCES CASA (id_casa),
    CONSTRAINT fk_multa_creado_por FOREIGN KEY (creado_por) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_multa_modificado_por FOREIGN KEY (modificado_por) REFERENCES USUARIO (id_usuario)
);

-- =====================================================================
-- 7. TABLA CUOTA
-- =====================================================================
CREATE TABLE CUOTA (
    id_cuota NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_cuota PRIMARY KEY,
    id_casa NUMBER NOT NULL,
    id_multa NUMBER CONSTRAINT uq_cuota_multa UNIQUE,
    concepto VARCHAR2(100) NOT NULL,
    periodo VARCHAR2(7) NOT NULL CONSTRAINT ck_cuota_periodo CHECK (REGEXP_LIKE(periodo, '^[0-9]{4}-(0[1-9]|1[0-2])$')),
    monto_total NUMBER(10,2) NOT NULL CONSTRAINT ck_cuota_monto CHECK (monto_total > 0),
    fecha_emision DATE DEFAULT SYSDATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL CONSTRAINT ck_cuota_estado CHECK (estado IN ('PENDIENTE', 'PARCIAL', 'PAGADA', 'VENCIDA', 'ANULADA')),
    creado_por NUMBER,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    modificado_por NUMBER,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT ck_cuota_fechas CHECK (fecha_vencimiento >= fecha_emision),
    CONSTRAINT fk_cuota_casa FOREIGN KEY (id_casa) REFERENCES CASA (id_casa),
    CONSTRAINT fk_cuota_multa FOREIGN KEY (id_multa) REFERENCES MULTA (id_multa),
    CONSTRAINT fk_cuota_creado_por FOREIGN KEY (creado_por) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_cuota_modificado_por FOREIGN KEY (modificado_por) REFERENCES USUARIO (id_usuario)
);

CREATE UNIQUE INDEX uq_cuota_periodica ON CUOTA (
    CASE WHEN id_multa IS NULL THEN id_casa END,
    CASE WHEN id_multa IS NULL THEN concepto END,
    CASE WHEN id_multa IS NULL THEN periodo END
);

-- =====================================================================
-- 8. TABLA PAGO
-- =====================================================================
CREATE TABLE PAGO (
    id_pago NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_pago PRIMARY KEY,
    id_cuota NUMBER NOT NULL,
    monto_pagado NUMBER(10,2) NOT NULL CONSTRAINT ck_pago_monto CHECK (monto_pagado > 0),
    fecha_pago DATE DEFAULT SYSDATE NOT NULL,
    metodo_pago VARCHAR2(20) NOT NULL CONSTRAINT ck_pago_metodo CHECK (metodo_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'DEPOSITO', 'TARJETA', 'OTRO')),
    referencia VARCHAR2(80),
    comprobante_url VARCHAR2(500),
    id_usuario_valida NUMBER,
    fecha_validacion DATE,
    observacion_rechazo VARCHAR2(250),
    estado VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL CONSTRAINT ck_pago_estado CHECK (estado IN ('PENDIENTE', 'VALIDO', 'RECHAZADO', 'ANULADO')),
    creado_por NUMBER,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    modificado_por NUMBER,
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_pago_cuota FOREIGN KEY (id_cuota) REFERENCES CUOTA (id_cuota),
    CONSTRAINT fk_pago_usuario_valida FOREIGN KEY (id_usuario_valida) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_pago_creado_por FOREIGN KEY (creado_por) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_pago_modificado_por FOREIGN KEY (modificado_por) REFERENCES USUARIO (id_usuario)
);

-- =====================================================================
-- 9. TABLA COMUNICADO
-- =====================================================================
CREATE TABLE COMUNICADO (
    id_comunicado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_comunicado PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_casa_destino NUMBER,
    titulo VARCHAR2(120) NOT NULL,
    contenido VARCHAR2(2000) NOT NULL,
    fecha_publicacion DATE DEFAULT SYSDATE NOT NULL,
    fecha_vencimiento DATE,
    estado VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL CONSTRAINT ck_comunicado_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_comunicado_fechas CHECK (fecha_vencimiento IS NULL OR fecha_vencimiento >= fecha_publicacion),
    CONSTRAINT fk_comunicado_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_comunicado_casa FOREIGN KEY (id_casa_destino) REFERENCES CASA (id_casa)
);

-- =====================================================================
-- 10. TABLA QUEJA
-- =====================================================================
CREATE TABLE QUEJA (
    id_queja NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_queja PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_casa NUMBER NOT NULL,
    asunto VARCHAR2(120) NOT NULL,
    descripcion VARCHAR2(2000) NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    estado VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL CONSTRAINT ck_queja_estado CHECK (estado IN ('PENDIENTE', 'EN_PROCESO', 'RESUELTA', 'RECHAZADA')),
    respuesta VARCHAR2(2000),
    fecha_respuesta DATE,
    CONSTRAINT fk_queja_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario),
    CONSTRAINT fk_queja_casa FOREIGN KEY (id_casa) REFERENCES CASA (id_casa)
);

-- =====================================================================
-- 11. TABLA AREA_COMUN
-- =====================================================================
CREATE TABLE AREA_COMUN (
    id_area NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_area_comun PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL CONSTRAINT uq_area_comun_nombre UNIQUE,
    descripcion VARCHAR2(250),
    capacidad NUMBER(4) CONSTRAINT ck_area_comun_capacidad CHECK (capacidad IS NULL OR capacidad > 0),
    ubicacion VARCHAR2(120),
    estado VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL CONSTRAINT ck_area_comun_estado CHECK (estado IN ('DISPONIBLE', 'NO_DISPONIBLE'))
);

-- =====================================================================
-- 12. TABLA RESERVACION
-- =====================================================================
CREATE TABLE RESERVACION (
    id_reservacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_reservacion PRIMARY KEY,
    id_residente NUMBER NOT NULL,
    id_area NUMBER NOT NULL,
    fecha_reserva DATE NOT NULL,
    hora_inicio VARCHAR2(5) NOT NULL CONSTRAINT ck_reservacion_hora_inicio CHECK (REGEXP_LIKE(hora_inicio, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    hora_fin VARCHAR2(5) NOT NULL CONSTRAINT ck_reservacion_hora_fin CHECK (REGEXP_LIKE(hora_fin, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    cantidad_personas NUMBER(4) NOT NULL CONSTRAINT ck_reservacion_cantidad CHECK (cantidad_personas > 0),
    motivo VARCHAR2(200),
    estado VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL CONSTRAINT ck_reservacion_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA')),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_reservacion_horas CHECK (hora_fin > hora_inicio),
    CONSTRAINT fk_reservacion_residente FOREIGN KEY (id_residente) REFERENCES RESIDENTE (id_residente),
    CONSTRAINT fk_reservacion_area FOREIGN KEY (id_area) REFERENCES AREA_COMUN (id_area)
);

-- =====================================================================
-- 13. TABLA VISITA (Visitas Anticipadas por el Condómino)
-- =====================================================================
CREATE TABLE VISITA (
    id_visita NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_visita PRIMARY KEY,
    id_casa NUMBER NOT NULL,
    id_residente NUMBER NOT NULL,
    nombre_visitante VARCHAR2(160) NOT NULL,
    identificacion VARCHAR2(30) NOT NULL,
    telefono_visitante VARCHAR2(20),
    fecha_esperada DATE DEFAULT SYSDATE NOT NULL,
    fecha_entrada DATE,
    fecha_salida DATE,
    motivo VARCHAR2(200),
    estado VARCHAR2(15) DEFAULT 'AUTORIZADA' NOT NULL CONSTRAINT ck_visita_estado CHECK (estado IN ('AUTORIZADA', 'DENTRO', 'FINALIZADA', 'CANCELADA', 'DENEGADA')),
    CONSTRAINT ck_visita_fechas CHECK (fecha_salida IS NULL OR fecha_salida >= fecha_entrada),
    CONSTRAINT fk_visita_casa FOREIGN KEY (id_casa) REFERENCES CASA (id_casa),
    CONSTRAINT fk_visita_residente FOREIGN KEY (id_residente) REFERENCES RESIDENTE (id_residente)
);

-- =====================================================================
-- 14. TABLA ACCESO (Control de Garita y Vigilancia)
-- =====================================================================
CREATE TABLE ACCESO (
    id_acceso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_acceso PRIMARY KEY,
    id_residente NUMBER,
    id_visita NUMBER,
    id_usuario_garita NUMBER NOT NULL,
    tipo_persona VARCHAR2(10) NOT NULL,
    tipo_movimiento VARCHAR2(10) NOT NULL CONSTRAINT ck_acceso_movimiento CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA')),
    fecha_hora TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    observacion VARCHAR2(250),
    CONSTRAINT ck_acceso_persona CHECK ((id_residente IS NOT NULL AND id_visita IS NULL) OR (id_residente IS NULL AND id_visita IS NOT NULL)),
    CONSTRAINT ck_acceso_tipo_persona CHECK (
        (tipo_persona = 'RESIDENTE' AND id_residente IS NOT NULL AND id_visita IS NULL) OR
        (tipo_persona = 'VISITANTE' AND id_visita IS NOT NULL AND id_residente IS NULL)
    ),
    CONSTRAINT fk_acceso_residente FOREIGN KEY (id_residente) REFERENCES RESIDENTE (id_residente),
    CONSTRAINT fk_acceso_visita FOREIGN KEY (id_visita) REFERENCES VISITA (id_visita),
    CONSTRAINT fk_acceso_garita FOREIGN KEY (id_usuario_garita) REFERENCES USUARIO (id_usuario)
);

-- =====================================================================
-- 15. TABLA BITACORA_AUDITORIA (Trazabilidad y Calidad RNF-05)
-- =====================================================================
CREATE TABLE BITACORA_AUDITORIA (
    id_auditoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_bitacora PRIMARY KEY,
    id_usuario NUMBER,
    usuario_afectado NUMBER,
    modulo VARCHAR2(40) NOT NULL,
    accion VARCHAR2(60) NOT NULL,
    tabla_afectada VARCHAR2(30),
    id_registro_afectado NUMBER,
    valor_anterior CLOB,
    valor_nuevo CLOB,
    ip_origen VARCHAR2(45) NOT NULL,
    user_agent VARCHAR2(250),
    fecha_hora TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bitacora_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario)
);

CREATE INDEX idx_bitacora_modulo_fecha ON BITACORA_AUDITORIA (modulo, fecha_hora);
CREATE INDEX idx_bitacora_usuario ON BITACORA_AUDITORIA (id_usuario);